from jarvis.execution.handlers.action_handlers import (
    OpenAppHandler,
    CloseAppHandler,
    WebSearchHandler,
    ReminderHandler,
    ClipboardHandler,
    FileOperationHandler,
    FolderOperationHandler,
    PCControlHandler,
    ScreenshotHandler,
    ScreenAwarenessHandler,
    SystemControlHandler,
    VolumeControlHandler,
    MemoryStoreHandler,
    MemoryRecallHandler,
    MemoryClearHandler,
    TimeHandler,
    DateHandler,
    SystemStatsHandler,
    MusicHandler,
    AIChatHandler,
    BrowserOpenHandler,
    BrowserSearchHandler,
    BrowserClickHandler,
    ClickHandler,
    DoubleClickHandler,
    RightClickHandler,
    TypeTextHandler,
    PressKeyHandler,
    ScrollHandler,
    HotkeyHandler,
    RunProgramHandler,
    RunTerminalCommandHandler,
    GenerateCodeHandler,
    WaitHandler,
    WaitForWindowHandler,
    WaitForElementHandler,
    SwitchWindowHandler,
    FocusWindowHandler,
    SearchInAppV2Handler,
    EmailHandler,
    WhatsAppHandler,
    CalendarEventHandler,
    SetReminderHandler,
    MoveMouseHandler,
)


def get_handlers():
    """Return a dictionary mapping action names to handler instances."""
    handler_classes = [
        OpenAppHandler,
        CloseAppHandler,
        WebSearchHandler,
        ReminderHandler,
        ClipboardHandler,
        FileOperationHandler,
        FolderOperationHandler,
        PCControlHandler,
        ScreenshotHandler,
        ScreenAwarenessHandler,
        SystemControlHandler,
        VolumeControlHandler,
        MemoryStoreHandler,
        MemoryRecallHandler,
        MemoryClearHandler,
        TimeHandler,
        DateHandler,
        SystemStatsHandler,
        MusicHandler,
        AIChatHandler,
        BrowserOpenHandler,
        BrowserSearchHandler,
        BrowserClickHandler,
        ClickHandler,
        DoubleClickHandler,
        RightClickHandler,
        TypeTextHandler,
        PressKeyHandler,
        ScrollHandler,
        HotkeyHandler,
        RunProgramHandler,
        RunTerminalCommandHandler,
        GenerateCodeHandler,
        WaitHandler,
        WaitForWindowHandler,
        WaitForElementHandler,
        SwitchWindowHandler,
        FocusWindowHandler,
        SearchInAppV2Handler,
        EmailHandler,
        WhatsAppHandler,
        CalendarEventHandler,
        SetReminderHandler,
        MoveMouseHandler,
    ]
    return {cls.__name__: cls() for cls in handler_classes}


def register_handlers(engine):
    """Register all handlers with the given engine."""
    handlers = get_handlers()
    for name, handler in handlers.items():
        engine.register_handler(name, handler)
