name: Bug report
description: Create a report to help us improve JARVIS
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run 'setup.bat'
        2. Speak 'Open Chrome'
        3. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please copy and paste any relevant error logs or console output.
